#!/usr/bin/env bash

HELP() {
    echo "ij: interstitial journal"
    echo
    echo "usage:"
    echo "       ij <journal message to record>"
    echo "       ij [flag|command]"
    echo
    echo "Flags"
    echo "    -t|t|today     Show only today"
    echo "    -c|c|clear     Clear all journal entries"
    echo "    -cp            Clear previous entries, keeping today"
}

ij_file=$HOME/.interstitial
[[ ! -f $ij_file ]] && touch $ij_file

splitchar='--'

color="--color=always"

view() {
    cat $ij_file | column -s'…' -t
}

view_3() {
    tail -n3 $ij_file | column -s'…' -t
}

view_today() {
    has_today=$(rg -q `date +%F` $ij_file)
    if [[ $? -eq 1 ]]; then
        echo "nothing today."
    else
        awk "/$(date +%F)/{start=1} start==1{print}" ~/.interstitial | column -s'…' -t
    fi
}

case $@ in
    '')
        view ;;
    -t|today|t)  # show only today
        view_today
        ;;
    -c|clear|c)   # Clear the journal
        echo "cleared."
        true > $ij_file
        ;;
    -cp)   # Clear previous entries
        echo "Cleared previous entries"
        view_today > $ij_file".bak"
        mv $ij_file".bak" $ij_file
        ;;
    -h|h|--help|help) HELP ;;
    *)   # append to interstitial journal
        has_today=$(rg -q `date +%F` $ij_file)
        if [[ $? -eq 1 ]]; then
            echo $(date +'%F %H:%M')" $splitchar $@" >> $ij_file
        else
            echo "           "$(date +'%H:%M')" $splitchar $@" >> $ij_file
        fi
        view_today
        ;;
esac

unset ij_file
