#!/usr/bin/env bash

inp="$@"
inp_no_ext="${@%%.pdf}"
out="$inp_no_ext"_nopasswd.pdf
echo "Removing password"
echo "  INPUT   $inp"
echo "  OUTPUT  $out"
gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$out $inp > /dev/null
