#!/usr/bin/env python3
import os
import sys
from pathlib import Path

ext = Path(sys.argv[1]).suffix
templates = list(Path(os.path.expanduser("~/.vim_file_templates")).glob(f"*{ext}"))
if templates:
    template = templates[0]
    print(template.read_text())
